const types = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  LOGIN: 'LOGIN',
  GET_BUYING_OPTIONS: 'GET_BUYING_OPTIONS',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
  GET_PRODUCTS: 'GET_PRODUCTS',
};

export default types;
