const types = {
  ADD_BUYING_OPTIONS: 'ADD_BUYING_OPTIONS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_ACCOUNT: 'GET_ACCOUNT',
  GET_BUYING_OPTIONS: 'GET_BUYING_OPTIONS',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
  GET_PRODUCTS: 'GET_PRODUCTS',
};

export default types;
